adjust_lr_dis: false
apdx: ''
aug_mode: simple
aug_s: true
aug_t: true
backbone: drunet
bd: 4
bs: 8
clahe: false
crop: 224
data_dir: ../../data/mscmrseg/origin
epochs: 1000
evalT: false
eval_bs: 32
filters: 32
fold: 0
hd95: false
lr: 0.00025
lr_decay: 0.002
lr_decay_method: null
lr_dis: 1.0e-05
lr_end: 0
mmt: 0.99
mmt1: 0.9
momentum: 0.9
multilvl: true
nb: 4
noM3AS: true
normalization: minmax
num_classes: 4
num_workers: 0
optim: sgd
percent: 100
pin_memory: false
power: 0.9
pretrained: true
raw: false
raw_data_dir: ../../data/mscmrseg/raw_data
restore_d: null
restore_d_aux: null
restore_from: ./weights/best_DR_UNet.baseline.lr0.00025.decay0.002.bs32.e252.Scr0.323.pt
rev: false
save_data: false
save_every_epochs: 50
scratch: false
seed: 1234
spacing: 1
split: 0
style_dir: ./style_track
toggle_klc: false
train_with_s: false
train_with_t: false
val_num: 0
vgg: pretrained/vgg_normalised.pth
w_dis: 0.01
w_dis_aux: 0.0002
w_seg_aux: 0.1
weight_decay: 0.0001
